name: cleanup
on: [workflow_dispatch]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: pandoc
          package-type: container
          min-versions-to-keep: 6
          delete-only-untagged-versions: true
